### ISSUE TITLE
wikilogic.com

### ISSUE THREAD

**Issue by ijmccallum** [WikiLogic/OrganisationIssues#39]
Domain expires Nov 21st (or at least it does with godaddy - no idea about the owner's agreement with godaddy).

We should probably look at picking this up one day

**Comment by douglassophies** [comment]
We should also look at the WL logo and the name copyright. Will be huge hassle to update it all if not allowed

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.1.1&source=email_footer_2] On Tue, Jun 14, 2016 at 5:54 pm, Iain J McCallum < notifications@github.com [notifications@github.com] > wrote:
Domain expires Nov 21st (or at least it does with godaddy - no idea about the owner's agreement with godaddy).

We should probably look at picking this up one day

**Comment by ijmccallum** [comment]
Aw :(
